### ISSUE TITLE
Keep getting error when trying to use XcodeSelectiveTesting

### ISSUE THREAD

**Issue by ichoosetoaccept** [mikeger/XcodeSelectiveTesting#28] opened 2024-09-25 20:11 UTC
Perhaps I misunderstood something in the readme and am not using this correctly, but I've:
- added the SPM dependency to Xcode
- right-clicked my project
- selected the XcodeSelectiveTesting plugin
- clicked "Run"

![CleanShot 2024-09-25 at 22 06 42@2x](https://github.com/user-attachments/assets/69c067d4-f0ab-40bb-861d-42488f00c621)

and I'm repeatedly getting this error:
error: Conflicting options '-warnings-as-errors' and '-suppress-warnings' (in target 'SelectiveTestShell' from project 'XcodeSelectiveTesting')

I've searched my entire project for these flags but cannot find them (both in the Xcode GUI and by searching through the whole project folder, starting from root, in terminal), nor do I remember ever setting these flags anywhere.

Am I the only one affected by this?

**Comment by mikeger** [comment] 2024-09-30 15:13
Hey @ichoosetoaccept , I see it as well with the latest compiler, let me make a hotfix.

**Comment by mikeger** [comment] 2024-10-01 07:31
@ichoosetoaccept can you give it a try with https://github.com/mikeger/XcodeSelectiveTesting/releases/tag/0.10.2 release?

**Comment by mikeger** [comment] 2024-10-31 10:37
I'll close this one for the time being, I think the issue is fixed. If not, feel free to re-open 👍

**Closed by mikeger** 2024-10-31 10:37 UTC

**Comment by ichoosetoaccept** [comment] 2024-10-31 11:33
Didn't get to reply in time.. but yes, the issue I had got resolved with this. Thanks!
